mappings_dict = {
    "CSE1235": {
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/CSE1235",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Specified Process Failure - After Refile Encounter": "Exception",
            "Validation Error - Encounter Number": "Exception",
            "End-to-End Success - CPT Updated to EST": "Success",
            "Unable to Click Hyperlink - Batch on Hold": "Exception",
            "Missing Mandatory Field - Missing Enc/Txn Number": "Exception",
            "New/Unexpected Screen Element - Procedure Code": "Exception",
            "Account Not Found - No Patient Found": "Exception",
            "Review Required by Northwell - Pending Representative Review": "Exception",
            "New/Unexpected Screen Element - IDX": "Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk": "Exception",
            "Unable to Click Hyperlink - Pending Representative Review": "Exception",
            "Specified Process Failure - Update Task Process": "Exception",
            "Unspecified Technical Failure - ": "Exception",
        },
        "scenario_crosswalk": {
            "Specified Process Failure - After Refile Encounter": "Technical error did not recognize a completed transaction",
            "Validation Error - Encounter Number": "Unable to validate encounter number",
            "End-to-End Success - CPT Updated to EST": "Successful transaction",
            "Unable to Click Hyperlink - Batch on Hold": "'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Missing Mandatory Field - Missing Enc/Txn Number": "Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - Procedure Code": "Procedure Codes do not populate in Enc/Txn screens",
            "Account Not Found - No Patient Found": "No search results for patient; Likely worked by another user",
            "Review Required by Northwell - Pending Representative Review": "Business rules applied to pend txn for further review",
            "New/Unexpected Screen Element - IDX": "Unexpected IDX Pop up",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk": "Input CPT does not have a value on the CPT Crosswalk",
            "Unable to Click Hyperlink - Pending Representative Review": "Technical Error prevented the bot from clicking the Pending Rep Review hyperlink",
            "Specified Process Failure - Update Task Process": "Technical Error prevented the bot from adding a note to the transaction",
            "Unspecified Technical Failure - ": "Unspecified technical error",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu; csperoni@northwell.edu',
        "name_format": "{file_path}/GECB_CSE1235_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Patient Name', 
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
        "BotName":"Claim Scrubber Edit 1235",
    },
    "CSE1236": {
        "BotName":"",
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/CSE1236",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "New/Unexpected Screen Element - No CPT populated":"Exception",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Exception",
            "Specified Process Failure - Unrecognized Success After Refile":"Exception",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Exception",
            "Validation Error - Encounter Number":"Exception",
            "Unable to Click Hyperlink - Batch on Hold":"Exception",
            "Unable to Click Hyperlink - Edit Multi Enc/Trn":"Exception",
            "New/Unexpected Screen Element - Encounter Edit List":"Exception",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Exception",
            "New/Unexpected Screen Element - Procedure Code":"Exception",
            "Validation Error - Within Edit Condition Description":"Exception",
            "Extraction Error - Edit Condition Description":"Exception",
            "New/Unexpected Screen Element - Edit Selector Header Screen":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "Known Pop Up - Edit CPT":"Exception",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"Exception",
            "Specified Process Failure - Update Task Process":"Exception",
            "New/Unexpected Screen Element - Encounter Number":"Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "End-to-End Success - CPT Updated to NEW":"Success",
            "Review Required by Northwell - Pending Representative Review":"Exception",
            "Unspecified Technical Failure - ":"Exception",
        },
        "scenario_crosswalk": {
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "New/Unexpected Screen Element - No CPT populated":"Procedure Codes do not populate in Enc/Txn screens",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Technical Error prevents accessing Edit Multi Enc/Trans hyperlink",
            "Specified Process Failure - Unrecognized Success After Refile":"Technical Error prevents recognition of successfully processed transaction",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Technical Error prevents identification of the Enc/Txn Edit screen",
            "Validation Error - Encounter Number":"Unable to validate encounter number",
            "Unable to Click Hyperlink - Batch on Hold":"'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Unable to Click Hyperlink - Edit Multi Enc/Trn":"Edit Multi Enc/Trn' hyperlink is unavailable; Likely due to Encounter in Use",
            "New/Unexpected Screen Element - Encounter Edit List":"No/Missing edit conditions on Edit Selector Header screen",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - Procedure Code":"New/Unexpected screen on either Enc/Txn Entry/Edit - Main screen",
            "Validation Error - Within Edit Condition Description":"Unable to validate CPT to be updated from Edit Decription text",
            "Extraction Error - Edit Condition Description":"Technical Error where unable to extract Edit Description text",
            "New/Unexpected Screen Element - Edit Selector Header Screen":"New/Unexpected screen on Edit Selector Header screen",
            "Account Not Found - No Patient Found":"No search results for patient; Likely worked by another user",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "Known Pop Up - Edit CPT":"Pop Up while editing 'Proc' value",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"New/Unexpected screen on either Enc/Txn editing screen",
            "Specified Process Failure - Update Task Process":"Technical Error prevented the bot from adding a note to the transaction",
            "New/Unexpected Screen Element - Encounter Number":"New/Unexpected screen on Patient/Encounter Selection screen",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "End-to-End Success - CPT Updated to NEW":"Successful Transaction",
            "Review Required by Northwell - Pending Representative Review":"Business rules applied to pend txn for further review",
            "Unspecified Technical Failure - ":"Unspecified Technical Error",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu; csperoni@northwell.edu',
        "name_format": "{file_path}/GECB_CSE1236_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Patient Name', 
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
        "BotName":"Claim Scrubber Edit 1236",
    },
    "TES1249": {
        "BotName":"TES1249",
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/TES1249",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "New/Unexpected Screen Element - Edit Selector Header Screen":"Exception",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"Exception",
            "New/Unexpected Screen Element - TES Inquiry Page":"Exception",
            "New/Unexpected Screen Element - View Header Page":"Exception",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Exception",
            "New/Unexpected Screen Element - Encounter Edit List":"Exception",
            "New/Unexpected Screen Element - Enc 1 in Edit Condition Description":"Exception",
            "New/Unexpected Screen Element - Enc 2 in Edit Condition Description":"Exception",
            "New/Unexpected Screen Element - Diagnosis Code":"Exception",
            "New/Unexpected Screen Element - Procedure Code":"Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "End-to-End Success - Modifier 24 Added":"Success",
            "Extraction Error - Edit Condition Description":"Exception",
            "Known Pop Up - Edit Modifier":"Exception",
            "Known Pop Up - Edit CPT":"Exception",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "End-to-End Success - CPT Updated to 99024":"Success",
            "Specified Process Failure - Update Task Process":"Exception",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Exception",
            "Unable to Click Hyperlink - Batch on Hold":"Exception",
            "Unable to Click Hyperlink - Pending Representative Review":"Exception",
            "Unable to Click Hyperlink - Edit Transaction":"Exception",
            "Validation Error - Encounter Number":"Exception",
            "Validation Error - Excessive Edit Descriptions":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "Review Required by Northwell - Pending Representative Review":"Exception",
            "Unspecified Technical Failure - ":"Exception",
            "Review Required by Northwell - Excessive Edit Descriptions":"Exception",
        },
        "scenario_crosswalk": {
            "New/Unexpected Screen Element - Edit Selector Header Screen":"Unable to detect the Edit Selector Header screen",
            "New/Unexpected Screen Element - Enc/Txn Edit Page":"Unable to detect the Enc/Txn Edit Screen",
            "New/Unexpected Screen Element - TES Inquiry Page":"Unable to detect the TES Inquiry Page",
            "New/Unexpected Screen Element - View Header Page":"Unable to detect the View Header screen",
            "New/Unexpected Screen Element - Enc Table in TES Enc/Txn Edit screen":"Unable to detect Enc Table in TES Enc/Txn Edit screen",
            "New/Unexpected Screen Element - Encounter Edit List":"Unable to detect edit conditions on Edit Selector Header screen",
            "New/Unexpected Screen Element - Enc 1 in Edit Condition Description":"Unable to detect encounter # 1 in Edit Condition text",
            "New/Unexpected Screen Element - Enc 2 in Edit Condition Description":"Unable to detect encounter # 2 in Edit Condition text",
            "New/Unexpected Screen Element - Diagnosis Code":"Diagnosis Code has not populated",
            "New/Unexpected Screen Element - Procedure Code":"Procedure Code has not populated",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Input CPT does not match a crosswalk value",
            "End-to-End Success - Modifier 24 Added":"Successfully added Mod 24",
            "Extraction Error - Edit Condition Description":"Unable to extract Edit Condition text",
            "Known Pop Up - Edit Modifier":"Pop Up while editing Modifier",
            "Known Pop Up - Edit CPT":"Pop Up while editing 'Proc'",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "End-to-End Success - CPT Updated to 99024":"Successfully update CPT to 99024",
            "Specified Process Failure - Update Task Process":"Technical Error prevented the bot from adding a note to the transaction",
            "Specified Process Failure - Edit Multiple Enc/Trans":"Technical Error prevents accessing Edit Multi Enc/Trans hyperlink",
            "Unable to Click Hyperlink - Batch on Hold":"'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Unable to Click Hyperlink - Pending Representative Review":"Technical Error prevented click of 'Pending Rep Review' hyperlink",
            "Unable to Click Hyperlink - Edit Transaction":"Technical Error prevented click of 'Edit Transaction' Hyperlink",
            "Validation Error - Encounter Number":"Unable to validate encounter number",
            "Validation Error - Excessive Edit Descriptions":"More Edit Descriptions encountered than expected",
            "Account Not Found - No Patient Found":"No search results for patient; Likely worked by another user",
            "Review Required by Northwell - Pending Representative Review":"Business rules applied to pend txn for further review",
            "Unspecified Technical Failure - ":"Unspecified Technical Error",
            "Review Required by Northwell - Excessive Edit Descriptions":"Excessive Edits requires additional review",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu; csperoni@northwell.edu',
        "name_format": "{file_path}/GECB_TES1249_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Patient Name', 
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "TES6146": {
        "BotName":"TES6146",
        "file_path": "M:/CPP-Data/Sutherland RPA/Coding/TES6146",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "CRN#",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
            "PROVFULLNAME",
            "Location",
        ],
        "status_crosswalk": {
            "Specified Process Failure - Email Not Sent to Provider":"Exception",
            "New/Unexpected Screen Element - Procedure Code":"Exception",
            "New/Unexpected Screen Element - Diagnosis Code":"Exception",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Exception",
            "End-to-End Success - Dx Pointers Reordered":"Success",
            "Known Pop Up - ICD-CM":"Exception",
            "Known Pop Up - Edit Dx Codes":"Exception",
            "End-to-End Success - Email Sent to Provider":"Success",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "Review Required by Northwell - Pending Representative Review":"Exception",
            "Specified Process Failure - Update Task Process":"Exception",
            "Specified Process Failure - Update DX Pointers":"Exception",
            "Missing Mandatory Field - Provider Email Address":"Exception",
            "Unable to Click Hyperlink - Batch on Hold":"Exception",
            "Unable to Click Hyperlink - Pending Feedback":"Exception",
            "Unable to Click Hyperlink - Pending Representative Review":"Exception",
            "Validation Error - Encounter Number":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "Unspecified Technical Failure - ":"Exception",
            "Review Required by Northwell - PRR - DX Pointers": "Exception",
            "Review Required by Northwell - PRR - Procedure Code":"Exception",
        },
        "scenario_crosswalk": {
            "Specified Process Failure - Email Not Sent to Provider":"Technical Error prevented email from being sent",
            "New/Unexpected Screen Element - Procedure Code":"Procedure Code has not populated",
            "New/Unexpected Screen Element - Diagnosis Code":"Diagnosis Code has not populated",
            "Crosswalk Discrepancy - Input CPT not on Crosswalk":"Bot unable to detect the value in the Proc field",
            "End-to-End Success - Dx Pointers Reordered":"Successfully reordered DX Pointers",
            "Known Pop Up - ICD-CM":"Pop Up stating Dx Code is not specific enough",
            "Known Pop Up - Edit Dx Codes":"Invalid Primary Diagnosis pop up",
            "End-to-End Success - Email Sent to Provider":"Successfully emailed Provider",
            "Missing Mandatory Field - Missing Enc/Txn Number":"Input File does not contain mandatory Enc/Txn numbers",
            "New/Unexpected Screen Element - IDX":"Unexpected IDX Pop up",
            "Review Required by Northwell - Pending Representative Review":"Business rules applied to pend txn for further review",
            "Specified Process Failure - Update Task Process":"Technical Error prevented the bot from adding a note to the transaction",
            "Specified Process Failure - Update DX Pointers":"Technical Error prevented the bot from updating Dx Pointers",
            "Missing Mandatory Field - Provider Email Address":"Input File does not contain mandatory Provider Email",
            "Unable to Click Hyperlink - Batch on Hold":"'Edit Transaction' hyperlink is not available; Likely Batch on Hold",
            "Unable to Click Hyperlink - Pending Feedback":"Technical Error prevented click of 'Pending Feedback' hyperlink",
            "Unable to Click Hyperlink - Pending Representative Review":"Technical Error prevented click of 'Pending Rep Review' hyperlink",
            "Validation Error - Encounter Number":"Unable to validate encounter number",
            "Account Not Found - No Patient Found":"No search results for patient; Likely worked by another user",
            "Unspecified Technical Failure - ":"Unspecified Technical Error",
            "Review Required by Northwell - PRR - DX Pointers": "Unable to update DX Pointers. Additional review required",
            "Review Required by Northwell - PRR - Procedure Code":"Unable to update DX Pointers. Additional review required",
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "Enc Number",
            "CRN#": "Txn Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
            "PROVFULLNAME": "Provider Name",
            "Location": "Division",
        },
        "carbon_copy": 'klawrence3@northwell.edu; ovicuna@northwell.edu; jcarney1@northwell.edu; gbunce@northwell.edu; mpuma@northwell.edu; csperoni@northwell.edu',
        "name_format": "{file_path}/GECB_TES6146_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Patient Name', 
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "MCD MCO Available": {
        "BotName":"MCD MCO Available",
        "file_path": "M:/FPP-CPP/Revenue Cycle Operations Training/Projects/RPA Project/MCD MCO Available",
        "columns": [
            "MRN",
            "Reason",
            "RetrievalStatus",
            "RetrievalDescription",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "C00-Completed - C00-Completed":"Success",
            "C00 - Payor is not available in the crosswalk - C00 - Payor is not available in the crosswalk":"Exception",
            "C00 - Data is not available under the Coverage section (eCN) - C00 - Data is not available under the Coverage section (eCN)":"Exception",
            "E07-Mandatory fields are missing in the received input - E07-Mandatory fields are missing in the received input":"Exception",
            "BE01-Unexpected screen occured  - BE01-Unexpected screen occured ":"Exception",
            "E03-BOT encountered unexpected screen elements or new screen and could not navigate - E03-BOT encountered unexpected screen elements or new screen and could not navigate":"Exception",
            "C00 - C00-No Data Availible for this Encounter - C00 - C00-No Data Availible for this Encounter":"Exception",
            "BE01-BE01-Non-HDX Payer - BE01-BE01-Non-HDX Payer":"Exception",
            "BE01-Special Characters Found error pop-up encountered. - E16-Special Characters Found error pop-up encountered.":"Exception",
            "E16-BOT encountered unexpected screen elements or new screen and could not navigate - E16-BOT encountered unexpected screen elements or new screen and could not navigate":"Exception",
            "BE01-Special Characters Found error pop-up encountered. - BE01-Special Characters Found error pop-up encountered.":"Exception",
            "E16-Coverage Tab is Empty - E16-Coverage Tab is Empty":"Exception",
            "E16-Failed to enter the account number into search box - E16-Failed to enter the account number into search box":"Exception",
            "E16-An Attending Physician is required. - E16-An Attending Physician is required.":"Exception",
            "New/Unexpected Screen Element - Revise Encounter Details":"Exception",
            "Account Not Found - No Encounter Found":"Exception",
            "Missing Information - eCN Coverage Screen Missing Info":"Exception",
            "Crosswalk Discrepancy - Missing Payor":"Exception",
            "New/Unexpected Screen Element - eCare Next":"Exception",
            "New/Unexpected Screen Element - Soarian":"Exception",
            "Missing Mandatory Field - Account Number / CIN":"Exception",
            "Login Error - eCare Next Credentials":"Exception",
            "Login Error - Soarian Credentials":"Exception",
            "New/Unexpected Screen Element - eCN Coverage Screen":"Exception",
            "Specified Process Failure - Encounter Search Process":"Exception",
            "Specified Process Failure - Enter Encounter Number":"Exception",
            "Specified Process Failure - Select Patient":"Exception",
            "New/Unexpected Screen Element - Soarian":"Exception",
            "Specified Process Failure - Select Work Queue":"Exception",
            "Account Not Found - No Encounter Found":"Exception",
            "Known Pop Up - Special Characters found":"Exception",
            "Crosswalk Discrepancy - Non-HDX Payer":"Exception",
            "End-to-End Success - MCD MCO Policy Added":"Success",
            "Unspecified Technical Failure - ":"Exception",
            "BE01-An Attending Physician is required. - BE01-An Attending Physician is required.":"Exception",
            """BE01-The below error occurred at Validation For Coordination of benefits
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at lambda_method(Closure , ActivityContext )
   at Microsoft.VisualBasic.Activities.VisualBasicValue`1.Execute(CodeActivityContext context)
   at System.Activities.Runtime.ActivityExecutor.ExecuteInResolutionContext[T](ActivityInstance parentInstance, Activity`1 expressionActivity)
   at System.Activities.InArgument`1.TryPopulateValue(LocationEnvironment targetEnvironment, ActivityInstance activityInstance, ActivityExecutor executor)
   at System.Activities.ActivityInstance.InternalTryPopulateArgumentValueOrScheduleExpression(RuntimeArgument argument, Int32 nextArgumentIndex, ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Boolean isDynamicUpdate)
   at System.Activities.ActivityInstance.ResolveArguments(ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Int32 startIndex)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation) - BE01-The below error occurred at Validation For Coordination of benefits
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at lambda_method(Closure , ActivityContext )
   at Microsoft.VisualBasic.Activities.VisualBasicValue`1.Execute(CodeActivityContext context)
   at System.Activities.Runtime.ActivityExecutor.ExecuteInResolutionContext[T](ActivityInstance parentInstance, Activity`1 expressionActivity)
   at System.Activities.InArgument`1.TryPopulateValue(LocationEnvironment targetEnvironment, ActivityInstance activityInstance, ActivityExecutor executor)
   at System.Activities.ActivityInstance.InternalTryPopulateArgumentValueOrScheduleExpression(RuntimeArgument argument, Int32 nextArgumentIndex, ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Boolean isDynamicUpdate)
   at System.Activities.ActivityInstance.ResolveArguments(ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Int32 startIndex)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)""":"Exception",
            "BE01-The Policy Number Does Not Match - BE01-The Policy Number Does Not Match":"Exception",
            "Coverage Tab is Empty - Coverage Tab is Empty":"Exception",
            "The Policy Number Does Not Match - ":"Exception",
            "New/Unexpected Screen Element - ":"Exception",
            "No Payer Identified in Terminated - ":"Exception",
            "New Popup identified - New Popup identified":"Exception",
            "No Data Availible for this Encounter - No Data Availible for this Encounter":"Exception",
            "The Policy Number Does Not Match - ":"Exception",
            "Payer not identified - ":"Exception",


        },
        "scenario_crosswalk": {
            "C00-Completed - C00-Completed":"End-to-end Success; MCD MCO Added",
            "C00 - Payor is not available in the crosswalk - C00 - Payor is not available in the crosswalk":"Payor not availabile in crosswalk",
            "C00 - Data is not available under the Coverage section (eCN) - C00 - Data is not available under the Coverage section (eCN)":"Data not found in eCareNext",
            "E07-Mandatory fields are missing in the received input - E07-Mandatory fields are missing in the received input":"Input File missing mandatory fields",
            "BE01-Unexpected screen occured  - BE01-Unexpected screen occured ":"Pop Up - No Policy Allocated",
            "E03-BOT encountered unexpected screen elements or new screen and could not navigate - E03-BOT encountered unexpected screen elements or new screen and could not navigate":"Pop Up - Workstation Closed",
            "C00 - C00-No Data Availible for this Encounter - C00 - C00-No Data Availible for this Encounter":"Account not found in Soarian",
            "BE01-BE01-Non-HDX Payer - BE01-BE01-Non-HDX Payer":"Non-HDX Payer",
            "BE01-Special Characters Found error pop-up encountered. - E16-Special Characters Found error pop-up encountered.":"Pop Up - Special Characters",
            "E16-BOT encountered unexpected screen elements or new screen and could not navigate - E16-BOT encountered unexpected screen elements or new screen and could not navigate":"New/Unexpected Screen in Soarian",
            "BE01-Special Characters Found error pop-up encountered. - BE01-Special Characters Found error pop-up encountered.":"Pop Up - Special Characters",
            "E16-Coverage Tab is Empty - E16-Coverage Tab is Empty":"Data not found in eCareNext",
            "E16-Failed to enter the account number into search box - E16-Failed to enter the account number into search box":"Technical Error prevented searching for patient in Soarian",
            "E16-An Attending Physician is required. - E16-An Attending Physician is required.":"Pop Up - Attending Physician",
            "New/Unexpected Screen Element - Revise Encounter Details":"Revise Encounter Details menu item is not available",
            "Account Not Found - No Encounter Found":"No search results available for the given encounter",
            "Missing Information - eCN Coverage Screen Missing Info":"Required data is not available under the eCN coverage section",
            "Crosswalk Discrepancy - Missing Payor":"Payor in question is not available in the crosswalk",
            "New/Unexpected Screen Element - eCare Next":"Bot encounters an unexpected screen element or a new screen and could not navigate",
            "New/Unexpected Screen Element - Soarian":"Bot encounters an unexpected pop-up or screen",
            "Missing Mandatory Field - Account Number / CIN":"Input does not provide the mandatory data for the bot",
            "Login Error - eCare Next Credentials":"Bot fails to login to the application due to a credentials issue",
            "Login Error - Soarian Credentials":"Bot fails to login to the application due to a credentials issue",
            "New/Unexpected Screen Element - eCN Coverage Screen":"eCN Coverage screen does not populate the required information due to application/latency issues",
            "Specified Process Failure - Encounter Search Process":"Bot fails to perform the encounter search step due to technical issues",
            "Specified Process Failure - Enter Encounter Number":"Bot fails to enter the encounter number in the Revise Encounter Details screen due to technical issues",
            "Specified Process Failure - Select Patient":"Bot fails to select the account due to technical issues",
            "New/Unexpected Screen Element - Soarian":"Bot encounters a new/unexpected screen element  towards the end of the workflow",
            "Specified Process Failure - Select Work Queue":"Bot unable to select the eCN Work Queue",
            "Account Not Found - No Encounter Found":"Encounter search does not populate any results in Soarian",
            "Known Pop Up - Special Characters found":"Special Characters Pop Up",
            "Crosswalk Discrepancy - Non-HDX Payer":"When the bot works NON-HDX crosswalk values",
            "End-to-End Success - MCD MCO Policy Added":"Successful transaction (end-to-end)",
            "Unspecified Technical Failure - ":"When the bot comes to a halt due to an unhandled exception",
            "BE01-An Attending Physician is required. - BE01-An Attending Physician is required.":"Pop Up - Attending Physician",
            """BE01-The below error occurred at Validation For Coordination of benefits
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at lambda_method(Closure , ActivityContext )
   at Microsoft.VisualBasic.Activities.VisualBasicValue`1.Execute(CodeActivityContext context)
   at System.Activities.Runtime.ActivityExecutor.ExecuteInResolutionContext[T](ActivityInstance parentInstance, Activity`1 expressionActivity)
   at System.Activities.InArgument`1.TryPopulateValue(LocationEnvironment targetEnvironment, ActivityInstance activityInstance, ActivityExecutor executor)
   at System.Activities.ActivityInstance.InternalTryPopulateArgumentValueOrScheduleExpression(RuntimeArgument argument, Int32 nextArgumentIndex, ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Boolean isDynamicUpdate)
   at System.Activities.ActivityInstance.ResolveArguments(ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Int32 startIndex)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation) - BE01-The below error occurred at Validation For Coordination of benefits
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at lambda_method(Closure , ActivityContext )
   at Microsoft.VisualBasic.Activities.VisualBasicValue`1.Execute(CodeActivityContext context)
   at System.Activities.Runtime.ActivityExecutor.ExecuteInResolutionContext[T](ActivityInstance parentInstance, Activity`1 expressionActivity)
   at System.Activities.InArgument`1.TryPopulateValue(LocationEnvironment targetEnvironment, ActivityInstance activityInstance, ActivityExecutor executor)
   at System.Activities.ActivityInstance.InternalTryPopulateArgumentValueOrScheduleExpression(RuntimeArgument argument, Int32 nextArgumentIndex, ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Boolean isDynamicUpdate)
   at System.Activities.ActivityInstance.ResolveArguments(ActivityExecutor executor, IDictionary`2 argumentValueOverrides, Location resultLocation, Int32 startIndex)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)""":"Unspecified Technical Error",
            "BE01-The Policy Number Does Not Match - BE01-The Policy Number Does Not Match":"Pop Up - Policy does not match expected format",
            "Coverage Tab is Empty - Coverage Tab is Empty":"Data not found in eCareNext",
            "The Policy Number Does Not Match - ":"Pop Up - Policy does not match expected format",
            "New/Unexpected Screen Element - ":"New/Unexpected Screen in Soarian",
            "No Payer Identified in Terminated - ":"Terminated Plan not found in well",
            "New Popup identified - New Popup identified":"New/Unexpected Screen in Soarian",
            "No Data Availible for this Encounter - No Data Availible for this Encounter":"Account not found in Soarian",
            "The Policy Number Does Not Match - ":"Bot receives pop-up stating policy number format is incorrect",
            "Payer not identified - ":"Terminated Plan not found in well",

        },
        "column_crosswalk": {
            "MRN": "Enc Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
        },
        "carbon_copy": 'mliffland2@northwell.edu; cgilroy@northwell.edu; jpanico@northwell.edu',
        "name_format": "{file_path}/eCareNext_MCDMCO_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [ 
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "MCR Advantage": {
        "BotName":"MCR Advantage",
        "file_path": "M:/FPP-CPP/Revenue Cycle Operations Training/Projects/RPA Project/MCR Advantage",
        "columns": [
            "MRN",
            "VisitIDCode",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "C00 - Plan Code not available in given Master Sheet - C00 - Plan Code not available in given Master Sheet":"Exception",
            "E16-BOT encountered unexpected screen elements or new screen and could not navigate - E16-BOT encountered unexpected screen elements or new screen and could not navigate":"Exception",
            "C00 - Completed - C00 - Completed":"Success",
            "C00 - Data is not available under the Coverage section (eCN) - C00 - Data is not available under the Coverage section (eCN)":"Exception",
            "C00 - Plan Code not present in Ecare - C00 - Plan Code not present in Ecare":"Exception",
            "E03-BOT encountered unexpected screen elements or new screen and could not navigate - E03-BOT encountered unexpected screen elements or new screen and could not navigate":"Exception",
            "E16-Unexpected screen occured, finish Revise not loaded - E16-Unexpected screen occured, finish Revise not loaded":"Exception",
            "E16-Unexpected screen occured eligibilityhyperlink not available - E16-Unexpected screen occured eligibilityhyperlink not available":"Exception",
            "C00 - C00-No Data Availible for this Encounter - C00 - C00-No Data Availible for this Encounter":"Exception",
            "C00 - C00-Completed - C00 - C00-Completed":"Success",
            "E16-Unexpected screen  occured, Insurence Eligibility header not found - E16-Unexpected screen  occured, Insurence Eligibility header not found":"Exception",
            "BE01-BE01-Non-HDX Payer - BE01-BE01-Non-HDX Payer":"Exception",
            "BE01-Special Characters Found error pop-up encountered. - BE01-Special Characters Found error pop-up encountered.":"Exception",
            "BE01-No matcheds found for the invoice - BE01-No matcheds found for the invoice":"Exception",
            "E16-Failed to select the patient - E16-Failed to select the patient":"Exception",
            "E16-Failed to enter the account number into search box - E16-Failed to enter the account number into search box":"Exception",
            "BE01-Revise Encounter Details Option Not Found - BE01-Revise Encounter Details Option Not Found":"Exception",
            "E16-Coverage Tab is Empty - E16-Coverage Tab is Empty":"Exception",
            "E16-The Policy Number Does Not Match - E16-The Policy Number Does Not Match":"Exception",
            "BE01-The Policy Number Does Not Match - BE01-The Policy Number Does Not Match":"Exception",
            "New/Unexpected Screen Element - Revise Encounter Details":"Exception",
            "Account Not Found - No Encounter Found":"Exception",
            "End-to-End Success - MCR Adv Policy Added":"Success",
            "Missing Information - eCN Coverage Screen Missing Info":"Exception",
            "Crosswalk Discrepancy - Missing Plan Code":"Exception",
            "New/Unexpected Screen Element - eCare Next":"Exception",
            "Specified Process Failure - Encounter Search Process":"Exception",
            "New/Unexpected Screen Element - Soarian":"Exception",
            "Missing Mandatory Field - Account Number / MBI":"Exception",
            "Login Error - eCare Next Credentials":"Exception",
            "Login Error - Soarian Credentials":"Exception",
            "New/Unexpected Screen Element - eCN Coverage Screen":"Exception",
            "Specified Process Failure - Enter Encounter Number":"Exception",
            "Specified Process Failure - Select Patient":"Exception",
            "Specified Process Failure - Select Work Queue":"Exception",
            "New/Unexpected Screen Element - Soarian":"Exception",
            "New/Unexpected Screen Element - Soarian - Insurance Eligibility header":"Exception",
            "Unable to Click Hyperlink - Soarian - Unspecified":"Exception",
            "New/Unexpected Screen Element - Soarian - Finish Revise":"Exception",
            "New/Unexpected Screen Element - Soarian - Insurance page":"Exception",
            "Account Not Found - No Encounter Found":"Exception",
            "Known Pop Up - Special Characters found":"Exception",
            "Crosswalk Discrepancy - Non-HDX Payer":"Exception",
            "Known Pop Up - Policy Number Format":"Exception",
            "Unspecified Technical Failure - ":"Exception",
            "BE01-An Attending Physician is required. - BE01-An Attending Physician is required.":"Exception",
            "New/Unexpected Screen Element - Encounter Search Process":"Exception",
            "An Attending Physician is required. - ":"Exception",
            "The Policy Number Does Not Match - ":"Exception",
            "New/Unexpected Screen Element - ":"Exception",
            "Unexpected screen occured  - ":"Exception",
            "Mandatory fields are missing in the received input - Encounter Search Process":"Exception",
            "New/Unexpected Screen Element - Missing Plan Code":"Exception",
            "No Payer Identified in Terminated - ":"Exception",
            "No Data Availible for this Encounter - No Data Availible for this Encounter":"Exception",
            "End-to-End Success - MCD MCO Policy Added":"Success",
            "End-to-End Success - No Data Availible for this Encounter":"Exception",
            " - ":"Exception",

        },
        "scenario_crosswalk": {
            "C00 - Plan Code not available in given Master Sheet - C00 - Plan Code not available in given Master Sheet":"Plan Code not in Master Crosswalk",
            "E16-BOT encountered unexpected screen elements or new screen and could not navigate - E16-BOT encountered unexpected screen elements or new screen and could not navigate":"New/Unexpected Element - Soarian",
            "C00 - Completed - C00 - Completed":"End-to-end Success; MCR Adv Added",
            "C00 - Data is not available under the Coverage section (eCN) - C00 - Data is not available under the Coverage section (eCN)":"Data not found in eCareNext",
            "C00 - Plan Code not present in Ecare - C00 - Plan Code not present in Ecare":"Plan Code Not Found in eCareNext",
            "E03-BOT encountered unexpected screen elements or new screen and could not navigate - E03-BOT encountered unexpected screen elements or new screen and could not navigate":"Pop Up - Workstation Closed",
            "E16-Unexpected screen occured, finish Revise not loaded - E16-Unexpected screen occured, finish Revise not loaded":"Finish Revise Encounter Pop Up Not Finished Loading",
            "E16-Unexpected screen occured eligibilityhyperlink not available - E16-Unexpected screen occured eligibilityhyperlink not available":"Unable to Launch eCareNext",
            "C00 - C00-No Data Availible for this Encounter - C00 - C00-No Data Availible for this Encounter":"Encounter not found after search in Soarian",
            "C00 - C00-Completed - C00 - C00-Completed":"End-to-end Success; MCR Adv Added",
            "E16-Unexpected screen  occured, Insurence Eligibility header not found - E16-Unexpected screen  occured, Insurence Eligibility header not found":"New/Unexpected Element - Soarian Eligibility Header",
            "BE01-BE01-Non-HDX Payer - BE01-BE01-Non-HDX Payer":"Non HDX Payer",
            "BE01-Special Characters Found error pop-up encountered. - BE01-Special Characters Found error pop-up encountered.":"Pop Up - Special Characters",
            "BE01-No matcheds found for the invoice - BE01-No matcheds found for the invoice":"Encounter not found after search in Soarian",
            "E16-Failed to select the patient - E16-Failed to select the patient":"Technical Error prevented selecting the patient in Soarian",
            "E16-Failed to enter the account number into search box - E16-Failed to enter the account number into search box":"Technical Error prevented bot from entering encounter number",
            "BE01-Revise Encounter Details Option Not Found - BE01-Revise Encounter Details Option Not Found":"Revised Encounter hyperlink not available",
            "E16-Coverage Tab is Empty - E16-Coverage Tab is Empty":"Technical error prevented data from being found in eCareNext",
            "E16-The Policy Number Does Not Match - E16-The Policy Number Does Not Match":"Pop Up - Invalid Policy Number Format",
            "BE01-The Policy Number Does Not Match - BE01-The Policy Number Does Not Match":"Pop Up - Invalid Policy Number Format",
            "New/Unexpected Screen Element - Revise Encounter Details":"Revise Encounter Details not available in Soarian",
            "Account Not Found - No Encounter Found":"No search results available for the given encounter",
            "End-to-End Success - MCR Adv Policy Added":"MCR Advantage Policy Added",
            "Missing Information - eCN Coverage Screen Missing Info":"Required data is not available under the eCN coverage section",
            "Crosswalk Discrepancy - Missing Plan Code":"Plan code not available in the crosswalk",
            "New/Unexpected Screen Element - eCare Next":"Bot encounters a new/unexpected screen element in eCN",
            "Specified Process Failure - Encounter Search Process":"Fails to perform the encounter search step due to technical issues",
            "New/Unexpected Screen Element - Soarian":"Bot encounters a new/unexpected screen element in Soarian",
            "Missing Mandatory Field - Account Number / MBI":"Input does not provide the mandatory data",
            "Login Error - eCare Next Credentials":"Bot fails to login to eCN due to a credentials issue",
            "Login Error - Soarian Credentials":"Bot fails to login to Soarian due to a credentials issue",
            "New/Unexpected Screen Element - eCN Coverage Screen":"eCN Coverage creen does not populate information due to application/latency issues",
            "Specified Process Failure - Enter Encounter Number":"Fails to enter the encounter number due to technical issues",
            "Specified Process Failure - Select Patient":"Fails to select the account due to technical issues",
            "Specified Process Failure - Select Work Queue":"Fails to select the eCN Work Queue",
            "New/Unexpected Screen Element - Soarian":"Bot encounters a new/unexpected screen element towards the end of the workflow",
            "New/Unexpected Screen Element - Soarian - Insurance Eligibility header":"Bot encounters a new/unexpected screen element regarding Insurance Eligibility Header",
            "Unable to Click Hyperlink - Soarian - Unspecified":"Unable to click a hyperlink in Soarian",
            "New/Unexpected Screen Element - Soarian - Finish Revise":"Bot encounters a new/unexpected screen element at the Finish Revise step",
            "New/Unexpected Screen Element - Soarian - Insurance page":"Bot encounters a new/unexpected screen element on the Insurance Eligibility info screen",
            "Account Not Found - No Encounter Found":"Encounter search does not populate any results in Soarian",
            "Known Pop Up - Special Characters found":"Bot encounters special characters pop up",
            "Crosswalk Discrepancy - Non-HDX Payer":"Bot worked NON-HDX crosswalk values",
            "Known Pop Up - Policy Number Format":"Bot encounters a policy number format mismatch pop up.",
            "Unspecified Technical Failure - ":"Bot comes to a halt due to an unhandled exception",
            "BE01-An Attending Physician is required. - BE01-An Attending Physician is required.":"Pop Up - Attending Phys Required",
            "New/Unexpected Screen Element - Encounter Search Process":"New/Unexpected Screen Element during the Encounter Search process",
            "An Attending Physician is required. - ":"Bot received an attending physician required pop up",
            "The Policy Number Does Not Match - ":"Bot received a pop up stating the policy number does not match expected format",
            "New/Unexpected Screen Element - ":"New/Unexpected Screen Element",
            "Unexpected screen occured  - ":"New/Unexpected Screen Element",
            "Mandatory fields are missing in the received input - Encounter Search Process":"Unspecified Technical Error",
            "New/Unexpected Screen Element - Missing Plan Code":"Plan Code not in Master Crosswalk",
            "No Payer Identified in Terminated - ":"Terminated Plan not found in well",
            "No Data Availible for this Encounter - No Data Availible for this Encounter":"Account not found in Soarian",
            "End-to-End Success - MCD MCO Policy Added":"End-to-end Success; MCR Adv Added",
            "End-to-End Success - No Data Availible for this Encounter":"Account not found in Soarian",
            " - ":"Manually Excluded Volume",

        },
        "column_crosswalk": {
            "MRN": "Enc Number",
            "VisitIDCode": "MCR Plan Code",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
        },
        "carbon_copy": 'mliffland2@northwell.edu; cgilroy@northwell.edu; jpanico@northwell.edu',
        "name_format": "{file_path}/eCareNext_MCRAdvantage_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "MCR PartB Inactive": {
        "BotName":"MCR Part B Inactive",
        "file_path": "M:/FPP-CPP/Revenue Cycle Operations Training/Projects/RPA Project/MCR PartB Inactive",
        "columns": [
            "MRN",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "C00-Unallocated Polices - ":"Success",
            "BE01-Pop-up error states a patient insurance policy needs to be allocated to this encounter - ":"Exception",
            "BE01-Special Characters Found error pop-up encountered. - ":"Exception",
            "BE01-Special Characters Found error pop-up encountered. - Patient Information page does not exists":"Exception",
            "C00-Policies are not available under Allocated Policies - ":"Exception",
            "C00-No Data Availible for this Encounter - ":"Exception",
            "Known Pop Up - Attending Phys Req":"Exception",
            "New/Unexpected Screen Element - Revise Encounter Details":"Exception",
            "Account Not Found - No Encounter Found":"Exception",
            "Known Pop Up - No Insurance Allocated":"Exception",
            "New/Unexpected Screen Element - Encounter Details ":"Exception",
            "New/Unexpected Screen Element - Patient Information":"Exception",
            "Specified Process Failure - Unallocate Policies":"Exception",
            "Missing Mandatory Field - Account Number":"Exception",
            "Specified Process Failure - Unallocate Policies":"Exception",
            "Specified Process Failure - Encounter Search Process":"Exception",
            "Known Pop Up - Special Characters found":"Exception",
            "End-to-End Success - Medicare Unallocated":"Success",
            "BE01-Revise Encounter Details Option Not Found - Revise Encounter Details Option Not Found": "Exception",
            "BE01-Pop-up error states a patient insurance policy needs to be allocated to this encounter - Pop-up error states a patient insurance policy needs to be allocated to this encounter":"Exception",
            "Unhandled Exception - Finish Revised Encounter Popup not found":"Exception"
        },
        "scenario_crosswalk": {
            "C00-Unallocated Polices - ":"End-to-end Success; MCR Part B unallocated",
            "BE01-Pop-up error states a patient insurance policy needs to be allocated to this encounter - ":"Pop Up - No Allocated Policies",
            "BE01-Special Characters Found error pop-up encountered. - ":"Pop Up - Special Characters",
            "BE01-Special Characters Found error pop-up encountered. - Patient Information page does not exists":"Pop Up - Special Characters",
            "C00-Policies are not available under Allocated Policies - ":"Pop Up - No Allocated Policies",
            "C00-No Data Availible for this Encounter - ":"Encounter Not Found after search in Soarian",
            "Known Pop Up - Attending Phys Req":"Bot encounters Attending Phys Req pop-up",
            "New/Unexpected Screen Element - Revise Encounter Details":"Revise Encounter Details is not available in Soarian",
            "Account Not Found - No Encounter Found":"No search results available for the given encounter",
            "Known Pop Up - No Insurance Allocated":"No policies listed under the Allocated Policies section",
            "New/Unexpected Screen Element - Encounter Details ":"Bot fails to detect the Encounter Details page due to technical issues",
            "New/Unexpected Screen Element - Patient Information":"Bot fails to detect the Patient Information page due to technical ssues",
            "Specified Process Failure - Unallocate Policies":"Bot encounters a new/unexpected screen element when unallocating insurance",
            "Missing Mandatory Field - Account Number":"Input does not provide the mandatory data",
            "Specified Process Failure - Unallocate Policies":"Bot is fails to unallocate a policy due to technical issues",
            "Specified Process Failure - Encounter Search Process":"Bot fails to perform the encounter search step due to technical issues",
            "Known Pop Up - Special Characters found":"Bot encounters special characters pop up",
            "End-to-End Success - Medicare Unallocated":"Medicare Part B Unallocated",
            "BE01-Revise Encounter Details Option Not Found - Revise Encounter Details Option Not Found": "Order Policies option disabled. No secondary policy allocated",
            "BE01-Pop-up error states a patient insurance policy needs to be allocated to this encounter - Pop-up error states a patient insurance policy needs to be allocated to this encounter":"Pop Up - No Policies Allocated",
            "Unhandled Exception - Finish Revised Encounter Popup not found":"Finish Revised Encounter window did not display"
        },
        "column_crosswalk": {
            "MRN": "Enc Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
        },
        "carbon_copy": 'mliffland2@northwell.edu; cgilroy@northwell.edu; jpanico@northwell.edu',
        "name_format": "{file_path}/eCareNext_MCRPartB_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "CPE": {
        "BotName":"MedicarePartBCPE",
        "file_path": "M:/FPP-CPP/Revenue Cycle Operations Training/Projects/RPA Project/CPE Medicine/Outputs",
        "columns": [
            "GECBMRN",
            "INVNUM",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "No Data Found - No Data Available after search in soarian":"Exception",
            "END - END Sucess - Medicare Comment Extracted  Sucessfully":"Success",
            " - SLS: MED Patient is scheduled for CPE or ANN NOT PRESENT":"Exception",
            "E03-New/Unexpected Screen Element - Eligibility Date is Not Present in Benfit Description":"Exception",
            " - Unhandled exception":"Exception",
            "Known Pop Up - Special Characters":"Exception",
            "E03-New/Unexpected Screen Element - Medicare Tab is not available under the Coverage section (eCN)":"Exception",
            "E03-New/Unexpected Screen Element - Medicare Comment Extracted  Sucessfully":"Exception",
            "Medicare Part B not found in Insurance tab - Unhandled exception":"Exception",
            "Codify comments are Not Present - Eligibility Date is Not Presnt in Benfit Description":"Exception",
            "New/Unexpected Screen Element - New/Unexpected Screen Element":"Exception",
            "Failed to Update Reason in Soarian - Bot failed to select correct row from Patient Appointments Table":"Exception",
            "Missing Information - Eligibility Date is Not Present in Benfit Description":"Exception",
            "Missing Information - Medicare Tab is not available under the Coverage section (eCN)":"Exception",
            "nan - nan":"Exception",
            "Missing Information - Eligibility Date Not Present":"Exception",
            "Missing Information - Medicare Part B Not found on Insurance Tab":"Exception",
            "Missing Information - Medicare Tab Not Available (eCN)":"Exception",
            "Ecare-Benifit Request Submited - Medicare Comment Extracted  Sucessfully":"Success",
            "BOT encountered unexpected screen elements or new screen and could not navigate - Unhandled exception":"Exception",
            " - ":"Exception",
            " - Coverage Tab is Empty":"Exception",
            " - Eligibility Date Not Present":"Exception",

        },
        "scenario_crosswalk": {
            "No Data Found - No Data Available after search in soarian":"No Encounter returned after search in Soarian Financials",
            "END - END Sucess - Medicare Comment Extracted  Sucessfully":"End-to-end Success",
            " - SLS: MED Patient is scheduled for CPE or ANN NOT PRESENT":"No appointment that matches criteria in Appointment Management",
            "E03-New/Unexpected Screen Element - Eligibility Date is Not Present in Benfit Description":"Bot unable to detect Eligibility Date in eCN",
            " - Unhandled exception":"Unspecified Technical Exception",
            "Known Pop Up - Special Characters":"Pop Up - Special Characters",
            "E03-New/Unexpected Screen Element - Medicare Tab is not available under the Coverage section (eCN)":"Bot unable to detect Medicare Tab in eCN",
            "E03-New/Unexpected Screen Element - Medicare Comment Extracted  Sucessfully":"Bot unable to determine CPE Eligibility Comment",
            "Medicare Part B not found in Insurance tab - Unhandled exception":"Medicare Part B not present in eCN Coverage Tab",
            "Codify comments are Not Present - Eligibility Date is Not Presnt in Benfit Description":"Eligibility Date not present in eCN Coverage Tab",
            "New/Unexpected Screen Element - New/Unexpected Screen Element":"Unspecified New Screen Element",
            "Failed to Update Reason in Soarian - Bot failed to select correct row from Patient Appointments Table":"Bot unable to update visit comment in Soarian Financials",
            "Missing Information - Eligibility Date is Not Present in Benfit Description":"Eligibility Date not present in eCN Coverage Tab",
            "Missing Information - Medicare Tab is not available under the Coverage section (eCN)":"Medicare Tab is not present in eCN Coverage Tab",
            "nan - nan":"Manually Excluded Volume",
            "Missing Information - Eligibility Date Not Present":"Eligibility Date not present in eCN Coverage Tab",
            "Missing Information - Medicare Part B Not found on Insurance Tab":"Medicare Tab is not present in eCN Coverage Tab",
            "Missing Information - Medicare Tab Not Available (eCN)":"Medicare Tab is not present in eCN Coverage Tab",
            "Ecare-Benifit Request Submited - Medicare Comment Extracted  Sucessfully":"End-to-end Success",
            "BOT encountered unexpected screen elements or new screen and could not navigate - Unhandled exception":"Unspecified New Screen Element",
            " - ":"Manually Excluded Volume",
            " - Coverage Tab is Empty":"Manually Excluded Volume",
            " - Eligibility Date Not Present":"Manually Excluded Volume",

        },
        "column_crosswalk": {
            "GECBMRN":"MRN",
            "INVNUM": "Enc Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
        },
        "carbon_copy": 'mliffland2@northwell.edu; cgilroy@northwell.edu; jpanico@northwell.edu',
        "name_format": "{file_path}/CPE_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "Medicare Not Primary": {
        "BotName":"Medicare Not Primary",
        "file_path": "M:/FPP-CPP/Revenue Cycle Operations Training/Projects/RPA Project/Medicare Not Primary",
        "columns": [
            "INVNUM",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "C00-Health plans reordered - ":"Success",
            "BE01-Mandatory fields are missing in the received input - ":"Exception",
            "BE01-An Attending Physician is required. - ":"Exception",
            "BE01-Order policies for an encounter option not found/disabled. - ":"Exception",
            "C00-No data available - ":"Exception",
            "E16-BOT encountered unexpected screen elements or new screen and could not navigate - ":"Exception",
            "E16-E16-BOT encountered unexpected screen elements or new screen and could not navigate - ":"Exception",
            "BE01-Special Characters Found error pop-up encountered. - ":"Exception",
            "Missing Mandatory Field - Account Number":"Exception",
            "Known Pop Up - Attending Phys Req":"Exception",
            "Unable to Click Hyperlink - Order Policies Disabled":"Exception",
            "Login Error - Soarian Credentials":"Exception",
            "New/Unexpected Screen Element - Soarian":"Exception",
            "Specified Process Failure - Enter Encounter Number":"Exception",
            "Account Not Found - No Encounter Found":"Exception",
            "Known Pop Up - Special Characters found":"Exception",
            "End-to-End Success - Medicare Moved to Secondary":"Success",
            "Unspecified Technical Failure - ":"Exception",
            "C00-Health plans reordered - C00-Health plans reordered":"Success",
            "BE01-An Attending Physician is required. - BE01-An Attending Physician is required.":"Exception",
            "BE01-Order policies for an encounter option not found/disabled. - BE01-Order policies for an encounter option not found/disabled.": "Exception",
            "BE01-Known Pop Up - Attending Phys Req":"Exception",
            "BE01-Unable to Click Hyperlink - Order Policies Disabled":"Exception",
            "BE01-Known Pop Up - Special Characters found":"Exception",
        },
        "scenario_crosswalk": {
            "C00-Health plans reordered - ":"End-to-end Success; Plans reordered",
            "BE01-Mandatory fields are missing in the received input - ":"Input File missing mandatory fields",
            "BE01-An Attending Physician is required. - ":"Pop Up - Attending Physician",
            "BE01-Order policies for an encounter option not found/disabled. - ":"Order Policies hyperlink disabled",
            "C00-No data available - ":"Encounter Not Found after search in Soarian",
            "E16-BOT encountered unexpected screen elements or new screen and could not navigate - ":"New/Unexpected Screen",
            "E16-E16-BOT encountered unexpected screen elements or new screen and could not navigate - ":"New/Unexpected Screen",
            "BE01-Special Characters Found error pop-up encountered. - ":"Pop Up - Special Characters",
            "Missing Mandatory Field - Account Number":"Input does not provide the mandatory data",
            "Known Pop Up - Attending Phys Req":"Bot encounters Attending Phys Req pop up",
            "Unable to Click Hyperlink - Order Policies Disabled":"Bot unable to order policies due to no secondary insurance present",
            "Login Error - Soarian Credentials":"Bot fails to login to the application due to a credentials issue",
            "New/Unexpected Screen Element - Soarian":"Bot encounters a new/unexpected screen element",
            "Specified Process Failure - Enter Encounter Number":"Bot fails to enter the encounter number due to technical issues",
            "Account Not Found - No Encounter Found":"Encounter search does not populate any results in Soarian",
            "Known Pop Up - Special Characters found":"Bot encounters special characters pop up",
            "End-to-End Success - Medicare Moved to Secondary":"Medicare Moved to Secondary",
            "Unspecified Technical Failure - ":"Bot comes to a halt due to an unhandled exception",
            "C00-Health plans reordered - C00-Health plans reordered":"End-to-end Success; Plans reordered",
            "BE01-An Attending Physician is required. - BE01-An Attending Physician is required.":"Pop Up - Attending Physician",
            "BE01-Order policies for an encounter option not found/disabled. - BE01-Order policies for an encounter option not found/disabled.": "Order Policies option disabled; No Secondary payer allocated",
            "BE01-Known Pop Up - Attending Phys Req":"Pop Up - Attending Physician",
            "BE01-Unable to Click Hyperlink - Order Policies Disabled":"Order Policies hyperlink disabled",
            "BE01-Known Pop Up - Special Characters found":"Pop Up - Special Characters Found",
        },
        "column_crosswalk": {
            "INVNUM": "Enc Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
        },
        "carbon_copy": 'mliffland2@northwell.edu; cgilroy@northwell.edu; jpanico@northwell.edu',
        "name_format": "{file_path}/eCareNext_SOARIAN_Outbound_{month_str}{day_str}{year_str}.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "LIJ IS Printing": {
        "BotName":"Printing Itemized Statement",
        "file_path": "M:/FPPShare/FPP-Production/Itemized Statement HCX BOT",
        "columns": [
            "POLICYID",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Itemized Statement Printed - ": "Success",
            "C00-Invoice not found in PCS Screen - ": "Exception",
            "Account Not Found - No Invoice Found":"Exception",
            "New/Unexpected Screen Element - IDX - Printer Device Screen":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "Missing Mandatory Field - Invoice Number":"Exception",
            "New/Unexpected Screen Element - Patient Services Page":"Exception",
            "New/Unexpected Screen Element - Invoice Inquiry Page":"Exception",
            "New/Unexpected Screen Element - More Actions Page":"Exception",
            "New/Unexpected Screen Element - Demand Statement Hyperlink":"Exception",
            "New/Unexpected Screen Element - Demand/Reprint Page":"Exception",
            "New/Unexpected Screen Element - Select Invoice Page":"Exception",
            "Specified Process Failure - Select Invoice Process":"Exception",
            "New/Unexpected Screen Element - BAR Demand Statement Screen":"Exception",
            "Specified Process Failure - Enter Printer Device Name":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "End-to-End Success - Itemized Statement Printed":"Success",
            "Account Not Found - Not Group 3 Invoice":"Exception",
        },
        "scenario_crosswalk": {
            "Itemized Statement Printed - ": "End-to-end Success",
            "C00-Invoice not found in PCS Screen - ": "Specific Invoice not found; Likely Group 4/5/6 Invoice",
            "Account Not Found - No Invoice Found":"Invoice is not found in the application",
            "New/Unexpected Screen Element - IDX - Printer Device Screen":"Bot encounters an unexpected screen after entering the Device value",
            "New/Unexpected Screen Element - IDX":"Bot encounters a new/unexpected screen element in IDX",
            "Missing Mandatory Field - Invoice Number":"Input does not provide the mandatory details",
            "New/Unexpected Screen Element - Patient Services Page":"Bot fails to detect the Patient Services page due to technical issues",
            "New/Unexpected Screen Element - Invoice Inquiry Page":"Bot fails to detect the Invoice Inquiry page due to technical issues",
            "New/Unexpected Screen Element - More Actions Page":"Bot fails to detect the More Actions page due to technical issues",
            "New/Unexpected Screen Element - Demand Statement Hyperlink":"Bot fails to detect the Demand Statement hyperlink due to technical issues",
            "New/Unexpected Screen Element - Demand/Reprint Page":"Bot fails to detect the Demand /Reprint page due to technical issues",
            "New/Unexpected Screen Element - Select Invoice Page":"Bot fails to detect the Select Invoice page due to technical issues",
            "Specified Process Failure - Select Invoice Process":"Bot fails to select the invoice due to technical issues",
            "New/Unexpected Screen Element - BAR Demand Statement Screen":"Bot fails to detect the BAR Demand Statement screen due to technical issues",
            "Specified Process Failure - Enter Printer Device Name":"Bot fails to enter the Device value due to technical issues",
            "Account Not Found - No Patient Found":"Patient is not found for the given invoice/accout number",
            "End-to-End Success - Itemized Statement Printed":"Successful transaction (end-to-end)",
            "Account Not Found - Not Group 3 Invoice":"Invoice not found in the PCS Selector Filtering Form due to non-group 3 invoice",
        },
        "column_crosswalk": {
            "POLICYID": "Invoice Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'danselmin@northwell.edu; nmitrako@northwell.edu; ttaylor6@northwell.edu; dbenjamin3@northwell.edu; tclouden@northwell.edu; djoseph8@northwell.edu',
        "name_format": "{file_path}/{year_str}{month_str}{day_str}_PAANS_BOT_v2_OUTBOUND.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    "BD IS Printing": {
        "BotName":"BADDEBT-PrintingItemizedStatement",
        "file_path": "M:/CPP-Data/Sutherland RPA/BD IS Printing",
        "columns": [
            "POLICYID",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "Itemized Statement Printed - ":"Success",
            "C00-Invoice not found in PCS Screen - ":"Exception",
            "Account Not Found - No Invoice Found":"Exception",
            "New/Unexpected Screen Element - IDX - Printer Device Screen":"Exception",
            "New/Unexpected Screen Element - IDX":"Exception",
            "Missing Mandatory Field - Invoice Number":"Exception",
            "New/Unexpected Screen Element - Patient Services Page":"Exception",
            "New/Unexpected Screen Element - Invoice Inquiry Page":"Exception",
            "New/Unexpected Screen Element - More Actions Page":"Exception",
            "New/Unexpected Screen Element - Demand Statement Hyperlink":"Exception",
            "New/Unexpected Screen Element - Demand/Reprint Page":"Exception",
            "New/Unexpected Screen Element - Select Invoice Page":"Exception",
            "Specified Process Failure - Select Invoice Process":"Exception",
            "New/Unexpected Screen Element - BAR Demand Statement Screen":"Exception",
            "Specified Process Failure - Enter Printer Device Name":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "End-to-End Success - Itemized Statement Printed":"Success",
            "Account Not Found - Not Group 3 Invoice":"Exception",
            "Itemized Statement Printed - Itemized Statement Printed":"Success",
        },
        "scenario_crosswalk": {
            "Itemized Statement Printed - ":"End-to-end Success; Itemized Statement Printed",
            "C00-Invoice not found in PCS Screen - ":"Specific Invoice not found; Likely Group 4/5/6 Invoice",
            "Account Not Found - No Invoice Found":"Invoice is not found in the application",
            "New/Unexpected Screen Element - IDX - Printer Device Screen":"Bot encounters an unexpected screen after entering the Device value",
            "New/Unexpected Screen Element - IDX":"Bot encounters a new/unexpected screen element in IDX",
            "Missing Mandatory Field - Invoice Number":"Input does not provide the mandatory details",
            "New/Unexpected Screen Element - Patient Services Page":"Bot fails to detect the Patient Services page due to technical issues",
            "New/Unexpected Screen Element - Invoice Inquiry Page":"Bot fails to detect the Invoice Inquiry page due to technical issues",
            "New/Unexpected Screen Element - More Actions Page":"Bot fails to detect the More Actions page due to technical issues",
            "New/Unexpected Screen Element - Demand Statement Hyperlink":"Bot fails to detect the Demand Statement hyperlink due to technical issues",
            "New/Unexpected Screen Element - Demand/Reprint Page":"Bot fails to detect the Demand /Reprint page due to technical issues",
            "New/Unexpected Screen Element - Select Invoice Page":"Bot fails to detect the Select Invoice page due to technical issues",
            "Specified Process Failure - Select Invoice Process":"Bot fails to select the invoice due to technical issues",
            "New/Unexpected Screen Element - BAR Demand Statement Screen":"Bot fails to detect the BAR Demand Statement screen due to technical issues",
            "Specified Process Failure - Enter Printer Device Name":"Bot fails to enter the Device value due to technical issues",
            "Account Not Found - No Patient Found":"Patient is not found for the given invoice/accout number",
            "End-to-End Success - Itemized Statement Printed":"Successful transaction (end-to-end)",
            "Account Not Found - Not Group 3 Invoice":"Invoice not found in the PCS Selector Filtering Form due to non-group 3 invoice",
            "Itemized Statement Printed - Itemized Statement Printed":"End-to-end Success; Itemized Statement Printed",
        },
        "column_crosswalk": {
            "POLICYID": "Invoice Number",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'avais@northwell.edu; bcerami@northwell.edu; CSchumacher1@northwell.edu; ssirico@northwell.edu; eromero12@northwell.edu; ccruz2@northwell.edu; SMolina2@northwell.edu; Ccardinali@northwell.edu',
        "name_format": "{file_path}/{year_str}/{year_str}{month_str}{day_str}_PAANS_BADDEBT_IB_BOT_OUTBOUND.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    # NCOA must be the last item in this dictionary
    "NCOA": {
        "BotName":"Patient Address Update via NCOA",
        "file_path": "M:/FPPShare/FPP-Production/NCOA BOT",
        "columns": [
            "PTFULLNAME",
            "INVNUM",
            "RetrievalStatus",
            "RetrievalDescription",
            "Reason",
            "RD + Reason",
            "Business Status",
            "Business Scenario",
        ],
        "status_crosswalk": {
            "C00:New address Added successfully - ": "Success",
            "E07-Mandatory fields are missing in the received input - ": "Exception",
            "C00:Address Already Exist - ": "Success",
            "BE01:Invalid Zipcode - ": "Exception",
            "Invalid Input - Invalid EPI":"Exception",
            "Invalid Input - Invalid Zipcode":"Exception",
            "Invalid Input - Invalid Person Number":"Exception",
            "Encounter Already Worked - Address updated prior to bot touch":"Success",
            "Unable to Click Hyperlink - Address Change button disabled":"Exception",
            "Specified Process Failure - Deactivate Address":"Exception",
            "New/Unexpected Screen Element - Search Page":"Exception",
            "Specified Process Failure - Incorrect (Mail Returned) checkbox":"Exception",
            "Validation Error - New Address after change":"Exception",
            "Missing Mandatory Field - Missing Address/EPI":"Exception",
            "Specified Process Failure - Update Address":"Exception",
            "New/Unexpected Screen Element - Soarian":"Exception",
            "Account Not Found - No Patient Found":"Exception",
            "End-to-End Success - Address Updated in Soarian":"Success",
            "C00:Address Already Exist - Address Already Exist": "Success",
            "BE01:Invalid Zipcode - Invalid Zipcode": "Exception",
            "BE01:Patient Account not found in search - Patient Account not found in search":"Exception",
        },
        "scenario_crosswalk": {
            "C00:New address Added successfully - ": "End-to-end Success; Address Added",
            "E07-Mandatory fields are missing in the received input - ": "Input does not provide the mandatory data (EPI)",
            "C00:Address Already Exist - ": "Address already updated",
            "BE01:Invalid Zipcode - ": "Invalid Zip Code",
            "Invalid Input - Invalid EPI":"External Person ID value is not in the expected format",
            "Invalid Input - Invalid Zipcode":"System does not auto-populate the city, country and county values after entering the zip code",
            "Invalid Input - Invalid Person Number":"Person ID# validation is unsuccessful",
            "Encounter Already Worked - Address updated prior to bot touch":"Bot successfully validates that the existing address matches with the input",
            "Unable to Click Hyperlink - Address Change button disabled":"Address Changes button is disabled/greyed-out",
            "Specified Process Failure - Deactivate Address":"Bot fails to deactivate the address due to technical issues",
            "New/Unexpected Screen Element - Search Page":"Bot fails to enter/detect the search page due to technical issues",
            "Specified Process Failure - Incorrect (Mail Returned) checkbox":"When the bot fails to click the checkbox for Incorrect (Mail returned) due to technical issues",
            "Validation Error - New Address after change":"Bot fails to validate whether the updated address is visible in the Patient Demographics screen due to technical issues",
            "Missing Mandatory Field - Missing Address/EPI":"Input does not provide the mandatory data",
            "Specified Process Failure - Update Address":"Bot fails to update the address due to technical issues",
            "New/Unexpected Screen Element - Soarian":"Bot encounters a new/unexpected screen element",
            "Account Not Found - No Patient Found":"No matching values found in the system",
            "End-to-End Success - Address Updated in Soarian":"Bot Successfully updates the Address",
            "C00:Address Already Exist - Address Already Exist": "New Address already in Soarian for Patient",
            "BE01:Invalid Zipcode - Invalid Zipcode": "System does not auto-populate the city, country and county values after entering the zip code",
            "BE01:Patient Account not found in search - Patient Account not found in search":"No matching values found in the system"
        },
        "column_crosswalk": {
            "PTFULLNAME": "Patient Name",
            "INVNUM": "EDI",
            "RetrievalStatus": "Retrieval Status",
            "RetrievalDescription": "Retrieval Description",
            "Reason": "Reason",
        },
        "carbon_copy": 'danselmin@northwell.edu; nmitrako@northwell.edu',
        "name_format": "{file_path}/{year_str}{month_str}{day_str}.NSH.NCOA_OUTBOUND.xlsx",
        "ind_name_format": "{file_path}/{year_str}{month_str}{day_str}.NSH.NCOA{index_num}_OUTBOUND*.xlsx",
        "drop_columns": [
            'Retrieval Status', 
            'Retrieval Description', 
            'Reason', 
            'RD + Reason', 
            'Business Status'
        ],
    },
    # "Coding MR Pull": {
    #     "BotName":"MRAuditPull",
    #     "file_path": "M:/CPP-Data/Sutherland RPA/Coding/MR AP",
    #     "columns": [
    #         "UMGMRN",
    #         "INVNUM",
    #         "CRN#",
    #         "PTFULLNAME",
    #         "PROVFULLNAME",
    #         "RD + Reason",
    #         "RetrievalStatus",
    #         "RetrievalDescription",
    #         "NoteCount",
    #     ],
    #     "status_crosswalk": {

    #     },
    #     "scenario_crosswalk": {

    #     },
    #     "column_crosswalk": {
    #         "UMGMRN": "MG MRN",
    #         "INVNUM": "Enc Number",
    #         "CRN#": "Txn Number",
    #         "PTFULLNAME": "Patient Name",
    #         "PROVFULLNAME": "Provider Name",
    #         "NoteCount": "# of Records",
    #         "RetrievalStatus": "Retrieval Status",
    #         "RetrievalDescription": "Retrieval Description",

    #     },
    #     "carbon_copy": '',
    #     "name_format": "{file_path}/GECB_CodingMRAuditPull_Outbound_{month_str}{day_str}{year_str}.xlsx",
    #     "drop_columns": [
    #         'Retrieval Status', 
    #         'Retrieval Description', 
    #         'Reason', 
    #         'RD + Reason', 
    #         'Business Status'
    #     ],
    # },
}

